Make the format to fatal_error a format specifier so we get compiler saftey
Setting this magic attribute means if you don't pass enough arguments
we'll get an error like this:

    webfetcher.c:54:63: error: more '%' conversions than data arguments [-Werror,-Wformat]
        fatal_error("conch_webfetcher_get: curl_easy_init failed %d!");
                                                                 ~^